on:
  pull_request:
    paths:
      - "src/**"
      - "tools/**"
      - "Directory.Build.props"

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

jobs:
  build-pr:
    name: "Build PR #${{ github.event.pull_request.number }}"
    runs-on: self-hosted
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
      - name: Build
        run: "mkdir build && dotnet pack -o build -p:VersionSuffix=PR-${{ github.event.pull_request.number }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Moonlight-PR-${{ github.event.pull_request.number }}.zip
          path: ./build/*