on:
  push:
    paths:
      - "src/**"
      - "tools/**"

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

jobs:
  nightly:
    name: Publish Nightly
    runs-on: self-hosted
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
      - name: Build
        run: "./tools/nightly.sh"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Moonlight-Nightly-${{ env.BUILD_NUMBER }}.zip
          path: ./build/*