on:
  push:
    paths:
      - "src/**"
      - "tools/**"
      - "Directory.Build.props"

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

jobs:
  nightly:
    name: "Publish Nightly Commit [${{ github.sha[0] }}${{ github.sha[1] }}${{ github.sha[2] }}${{ github.sha[3] }}${{ github.sha[4] }}${{ github.sha[5] }}${{ github.sha[6] }}${{ github.sha[7] }}](${{ github.sha }})"
    runs-on: self-hosted
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'recursive'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
      - name: Build
        run: "./tools/nightly.sh ${{ github.ref }} ${{ secrets.NUGET_ORG_API_KEY }}"
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          DISCORD_CHANNEL_TOPIC: ${{ secrets.DISCORD_CHANNEL_TOPIC }}
          NUGET_URL: ${{ secrets.NUGET_URL }}
          GITHUB_URL : ${{ github.server_url }}/${{ github.repository }}
          LATEST_STABLE_VERSION: ${{ env.LATEST_STABLE_VERSION }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Moonlight-Nightly-${{ env.BUILD_NUMBER }}.zip
          path: ./build/*